kind = "mobile"
previewPath = "/"
title = "Мама и ребенок"
version = "1.0.0"
id = "artifacts/mama-i-rebenok"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18484

[services.development]
run = "pnpm --filter @workspace/mama-i-rebenok run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mama-i-rebenok", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/mama-i-rebenok", "run", "serve" ]

[services.env]
PORT = "18484"
BASE_PATH = "/"
